/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    RiAddFill: typeof import('@remixicon/vue')['RiAddFill']
    RiArrowLeftWideFill: typeof import('@remixicon/vue')['RiArrowLeftWideFill']
    RiArrowRightWideFill: typeof import('@remixicon/vue')['RiArrowRightWideFill']
    RiSubtractFill: typeof import('@remixicon/vue')['RiSubtractFill']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
